-- Supabase PostgreSQL Schema

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Courses Table
CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university TEXT NOT NULL,
  course_code TEXT NOT NULL,
  title TEXT NOT NULL,
  units TEXT,
  description TEXT,
  url TEXT,
  details JSONB,
  department TEXT,
  corequisites TEXT,
  level TEXT,
  difficulty DOUBLE PRECISION,
  popularity INTEGER DEFAULT 0,
  workload TEXT,
  is_hidden BOOLEAN DEFAULT FALSE,
  is_internal BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(university, course_code)
);

CREATE INDEX IF NOT EXISTS idx_courses_university ON courses(university);
CREATE INDEX IF NOT EXISTS idx_courses_course_code ON courses(course_code);

-- Fields Table
CREATE TABLE IF NOT EXISTS fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- Course-Fields Relationship
CREATE TABLE IF NOT EXISTS course_fields (
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  field_id BIGINT NOT NULL REFERENCES fields(id) ON DELETE CASCADE,
  PRIMARY KEY (course_id, field_id)
);

CREATE INDEX IF NOT EXISTS idx_course_fields_field ON course_fields(field_id);

-- User Courses Table (Linking to Supabase Auth)
CREATE TABLE IF NOT EXISTS user_courses (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  status TEXT DEFAULT 'pending', -- pending, in_progress, completed, dropped
  priority INTEGER DEFAULT 0,
  gpa NUMERIC(3,2) CHECK (gpa >= 0 AND gpa <= 5.0),
  score NUMERIC(5,2) CHECK (score >= 0 AND score <= 100),
  notes TEXT,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, course_id)
);

CREATE INDEX IF NOT EXISTS idx_user_courses_user ON user_courses(user_id);
CREATE INDEX IF NOT EXISTS idx_user_courses_status ON user_courses(status);

-- Semesters Table
CREATE TABLE IF NOT EXISTS semesters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INTEGER NOT NULL,
  term TEXT NOT NULL,
  UNIQUE(year, term)
);

-- Course-Semesters Relationship
CREATE TABLE IF NOT EXISTS course_semesters (
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  PRIMARY KEY (course_id, semester_id)
);

CREATE INDEX IF NOT EXISTS idx_course_semesters_semester ON course_semesters(semester_id);

-- Row Level Security (RLS)
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE semesters ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_semesters ENABLE ROW LEVEL SECURITY;

-- Policies
-- Public Read Access
CREATE POLICY "Allow public read access on courses" ON courses FOR SELECT USING (NOT is_hidden);
CREATE POLICY "Allow public read access on fields" ON fields FOR SELECT USING (true);
CREATE POLICY "Allow public read access on course_fields" ON course_fields FOR SELECT USING (true);
CREATE POLICY "Allow public read access on semesters" ON semesters FOR SELECT USING (true);
CREATE POLICY "Allow public read access on course_semesters" ON course_semesters FOR SELECT USING (true);

-- Authenticated User Access for user_courses
CREATE POLICY "Users can view their own enrollments" ON user_courses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own enrollments" ON user_courses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own enrollments" ON user_courses FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own enrollments" ON user_courses FOR DELETE USING (auth.uid() = user_id);

-- RPC Functions
CREATE OR REPLACE FUNCTION increment_popularity(row_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE courses
  SET popularity = popularity + 1
  WHERE id = row_id;
END;
$$;

-- Study Schedules Table
-- Stores user's planned study schedule for courses
CREATE TABLE IF NOT EXISTS study_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  scheduled_date DATE NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  duration_minutes INTEGER DEFAULT 60,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, course_id, scheduled_date)
);

CREATE INDEX IF NOT EXISTS idx_study_schedules_user ON study_schedules(user_id);
CREATE INDEX IF NOT EXISTS idx_study_schedules_date ON study_schedules(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_study_schedules_user_date ON study_schedules(user_id, scheduled_date);

-- Enable RLS for study_schedules
ALTER TABLE study_schedules ENABLE ROW LEVEL SECURITY;

-- Policies for study_schedules
CREATE POLICY "Users can view their own schedules" ON study_schedules FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own schedules" ON study_schedules FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own schedules" ON study_schedules FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own schedules" ON study_schedules FOR DELETE USING (auth.uid() = user_id);
