// Script to run study_schedules table migration
// Run with: npx tsx -r dotenv/config src/scripts/migrate-study-schedules.ts dotenv_config_path=.env.local

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: { persistSession: false }
});

const migrationSQL = `
-- Study Schedules Table
-- Stores user's planned study schedule for courses
CREATE TABLE IF NOT EXISTS study_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  scheduled_date DATE NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  duration_minutes INTEGER DEFAULT 60,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, course_id, scheduled_date)
);

CREATE INDEX IF NOT EXISTS idx_study_schedules_user ON study_schedules(user_id);
CREATE INDEX IF NOT EXISTS idx_study_schedules_date ON study_schedules(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_study_schedules_user_date ON study_schedules(user_id, scheduled_date);

ALTER TABLE study_schedules ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view their own schedules' AND tablename = 'study_schedules') THEN
    CREATE POLICY "Users can view their own schedules" ON study_schedules FOR SELECT USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can insert their own schedules' AND tablename = 'study_schedules') THEN
    CREATE POLICY "Users can insert their own schedules" ON study_schedules FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can update their own schedules' AND tablename = 'study_schedules') THEN
    CREATE POLICY "Users can update their own schedules" ON study_schedules FOR UPDATE USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can delete their own schedules' AND tablename = 'study_schedules') THEN
    CREATE POLICY "Users can delete their own schedules" ON study_schedules FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;
`;

async function runMigration() {
  console.log('🚀 Running study_schedules migration...');
  
  const { error } = await supabase.rpc('exec_sql', { sql: migrationSQL });
  
  if (error) {
    // If exec_sql doesn't exist, try running directly
    console.log('⚠️  exec_sql not available, trying direct query...');
    
    // Split and run each statement
    const statements = migrationSQL.split(';').filter(s => s.trim());
    
    for (const statement of statements) {
      if (statement.trim()) {
        const { error: stmtError } = await supabase.from('_dummy').select().limit(0);
        // Note: Supabase JS client doesn't support raw SQL, need to use dashboard
        console.log('Statement:', statement.substring(0, 50) + '...');
      }
    }
    
    console.log('\n⚠️  Cannot run raw SQL via Supabase JS client.');
    console.log('📋 Please run this SQL in your Supabase Dashboard:');
    console.log('   1. Go to https://supabase.com/dashboard');
    console.log('   2. Select your project');
    console.log('   3. Go to SQL Editor');
    console.log('   4. Paste and run the following SQL:\n');
    console.log('─'.repeat(60));
    console.log(migrationSQL);
    console.log('─'.repeat(60));
    return;
  }
  
  console.log('✅ Migration completed successfully!');
}

runMigration().catch(console.error);
